### ISSUE TITLE
The error "Cannot read property'then' of undefined" pops up

### ISSUE THREAD

**Issue by nodamushi** [whitphx/vscode-emacs-mcx#1270]
![image](https://user-images.githubusercontent.com/581955/159938194-d711f1f8-c4f7-4aca-a9b2-3c4cb9cec489.png)

## Environment

- OS: windows 10
- VS Code: 1.65.2
- Awesome Emacs Keymap: v0.41.1

## Log

```
[2022-03-24 23:10:18.570] [exthost] [error] TypeError: Cannot read property 'then' of undefined
	at c:\Users\●●●\.vscode\extensions\tuttieee.emacs-mcx-0.41.1\dist\extension.js:1:116920
	at Generator.next (<anonymous>)
	at o (c:\Users\●●●\.vscode\extensions\tuttieee.emacs-mcx-0.41.1\dist\extension.js:1:114569)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) emacs-mcx.isearchExit {"value":"tuttieee.emacs-mcx","_lower":"tuttieee.emacs-mcx"}
```

## Code

I think the code that is causing the problem is probably here.

https://github.com/whitphx/vscode-emacs-mcx/blob/09d84f9a1d926032a2d66f74e382fdd57055ee32/src/extension.ts#L143-L145

Thank you for developing a nice plugin!

**Comment by whitphx** [comment]
Thank you for the report.
This will be fixed in the next release.
